version: '3.3'
services:
  db:
    image: postgres:latest
    env_file:
      - ./blogProject/.env

  django:
    build: ./blogProject/
    command: python manage.py runserver 0.0.0.0:8080
    env_file:
      - ./blogProject/.env
    volumes:
      - .:/tmp
    ports:
      - "8080:8080"
    depends_on:
      - db
    working_dir: /tmp/blogProject
